name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: androidx/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle
      # در اینجا از دستور دقیق‌تری برای بیلد ماژول app استفاده می‌کنیم
      # و به جای نادیده گرفتن validateSigning، بیلد را مستقیم روی assembleDebug تنظیم می‌کنیم
      run: gradle :app:assembleDebug
